name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
  # Defult branch is master
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/NSA-7257
    - repository: config
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.config
      ref: master
    - repository: scripts
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.db-scripts
      ref: develop


trigger:
  branches:
    include:
    - release/*
    - feature/*

pr:
  branches:
    include:
    - develop

parameters:
- name: AppDeploy
  type: boolean
  displayName: 'Logic app workflow deployment only'
  default: true
- name: InfrDeploy
  type: boolean
  displayName: 'Infrastrucure Deployment only'
  default: false
- name: tran
  type: boolean
  displayName: 'Transformation Deployment'
  default: false
- name: dev
  type: boolean
  displayName: 'Dev Deployment'
  default: false
- name: test
  type: boolean
  displayName: 'Test Deployment'
  default: false
- name: pp
  type: boolean
  displayName: 'Pre-Prod Deployment'
  default: false
- name: pr
  type: boolean
  displayName: 'Prod Deployment'
  default: false

variables:
- group: dsi-global
- name: applicationShortName
  value: 'schwkr-la'
- name: applicationFullName
  value: 'searchWorkerLogicApp'
- name: tran
  ${{ if eq(parameters.tran, 'true') }}:
    value: true
  ${{ else }}:
    value: false
- name: dev
  ${{ if eq(parameters.dev, 'true') }}:
    value: true
  ${{ else }}:
    value: false
- name: test
  ${{ if or(eq(parameters.test, 'true'), contains(variables['Build.SourceBranch'],'develop')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pp
  ${{ if or(eq(parameters.pp, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false
- name: pr
  ${{ if or(eq(parameters.pr, 'true'), contains(variables['Build.SourceBranch'],'release')) }}:
    value: true
  ${{ else }}:
    value: false


stages:

# Code Scans & Build the artifact for deployment
- stage: scanBuildApp
  displayName: "Scan tools & Build"
  jobs:
    # Code scaning tools
  - template:  pipeline/checkov.yml@devopsTemplates

- ${{ each var in variables }}:
  - ${{ if in(var.key, 'tran','dev','test','pp','pr') }}:
    - ${{ if eq(var.value, 'true') }}:
      - stage: Deployment_${{var.Key}}
        displayName: "Deployment [${{var.Key}}]"
        dependsOn: 
        - scanBuildApp
        condition: in(dependencies.scanBuildApp.result, 'Succeeded', 'Skipped')
        variables:
        - group: dsi-${{var.key}}-kv
        jobs:
        - ${{ if parameters.InfrDeploy }}:
          - template: pipeline/appInfrastructure.yml@devopsTemplates
            parameters:
              ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(var.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{var.key}}
              applicationShortName: ${{variables.applicationShortName}}
              applicationFullName: ${{variables.applicationFullName}}
              releaseArtifactName: ${{variables.applicationFullName}}-${{var.key}}-$(Build.BuildId)-release
              ${{ if eq(var.key, 'pr') }}:
                certificateName: signin-generic
              ${{ else }}:
                certificateName: non-prod-gateway
              AppDeploy: ${{parameters.AppDeploy}}
              workerRepo: search
              logicAppRuntimeStack: ~18
              logicAppRuntime: node
              logicAppStandartVersion: ~4

        - ${{ if parameters.AppDeploy }}:
          - template: pipeline/logicAppDeploy.yml@devopsTemplates
            parameters: 
              ${{ if or(eq(var.key, 'dev'), eq(var.key, 'tran')) }}:
                serviceConnection: $(devServiceConnection)
              ${{ elseif eq(var.key, 'pr') }}:
                serviceConnection: $(prodServiceConnection)
              ${{ else }}:
                serviceConnection: $(testServiceConnection)
              environmentName: ${{var.key}}
              applicationShortName: ${{variables.applicationShortName}}
              workerRepo: search
              InfrDeploy: ${{parameters.InfrDeploy}}